packages:
  github.com/carlosgonzalez/go-bundled/internal/repositories:
    config:
      dir: mocks
      filename: "mock_{{.InterfaceName}}.go"
      pkgname: mocks
    interfaces:
      UserRepositoryInterface:
