name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  code-analysis:
    name: code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - uses: brokeyourbike/go-mockery-action@v0
        with:
          mockery-version: "3.2.5"

      - run: mockery

      - name: Linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

      - name: Vet
        run: go vet ./...

  unit-tests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: go get .

      - uses: brokeyourbike/go-mockery-action@v0
        with:
          mockery-version: "3.2.5"

      - run: mockery

      - name: Test with the Go CLI
        run: task test
