name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  code-analysis:
    name: code analysis
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Vet
        run: go vet ./...

  unit-tests:
    name: unit tests
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        run: go test -v ./...

  dependencies:
    name: mockery
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install dependencies
        run: go get .
      - uses: brokeyourbike/go-mockery-action@v0
        with:
          mockery-version: "2.42.0"
      - run: mockery --all
